name: Check derSchutze Stock

on:
  workflow_dispatch:   # allows manual trigger from GitHub UI
  repository_dispatch: # allows external trigger from cron-job.org

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install requests
      - name: Run stock checker
        run: python main.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
