name: Check derSchutze Stock

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes (UTC)
  workflow_dispatch:  # allows manual triggering

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install requests
      - name: Run stock checker
        run: python main.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
